- name: Mariadb playbook to deprovision the application
  hosts: localhost
  gather_facts: false
  connection: local
  roles:
    - role: ansible.kubernetes-modules
      install_python_requirements: no
    - role: deprovision-mariadb-apb
      playbook_debug: false
